### ISSUE TITLE
Dynamic height, smooth-scroll and gumshoe

### ISSUE THREAD

**Issue by inspiredlabs** [cferdinandi/smooth-scroll#323]
Expanding or collapsing the height of a DIV changes the overall height of the page, for example with an accordion.

This means that if you open an accordion (see the reduced test case) the class `active` is applied  without taking into account the new height of the page. Now, after any of them are open and you scroll using the mouse/trackpad the indicator (on the right column on the reduced test case) doesn't correspond with the new content height.

Reduced test case: http://inspiredlabs.co.uk/8/reduced-test-case.html

Is there a way to use smooth-scroll and gumshoe and also have content affect the height of the page?

**Comment by cferdinandi** [comment]
Short answer: yes.
Long answer: not the way you have your accordion configured.

Specifically, your use of `overflow: hidden` is what's causing the issues. The script cannot properly calculate heights and distances.

I would recommend using the following style instead:

```css
.accordion .article {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}

.accordion input:checked ~ .article.ac-default {
    clip: auto;
    height: auto;
    margin: 0;
    overflow: visible;
    position: static;
    width: auto;
}
```

This maintains the same accessibility you have now... as in, screen readers can access the content whether expanded or collapsed.

***Side note:*** *It's worth mentioning that your use of `transition` on `height` does not work with either your current or my recommend CSS, as height-based transitions require an absolute height value (ex. `200px`) and will not work with `auto`.*

With this new styling in place, you can call `gumshoe.setDistances();` after your accordion is opened or closed to recalculate the heights and distances of the content on the page. More on that here: https://github.com/cferdinandi/gumshoe#setdistances.
